Club_De_Fans/config/routes.rb
Rails.application.routes.draw do
  
  
  get 'sessions/new'

  get 'home/index'

  get 'home/contacto'

  get 'home/quienes_somos'

  get 'home/lista_comentarios'

  get 'home/eliminar'

  post 'home/crear_contacto' 

  root 'home#index'

  get 'usuarios/signup', to: 'usuarios#new'
  resources :usuarios

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post '/eventos/crear_comentario'
  post '/eventos/subir_imagen'
  get '/eventos/eliminar_comentario'

  resources :eventos
end

Club_De_Fans/app/models/evento.rb
class Evento < ActiveRecord::Base
end

Club_De_Fans/app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]
  before_action :usuario_iniciado, only: [:edit, :update]
  before_action :usuario_admin, only: [:destroy, :edit, :update]
  # GET /eventos
  # GET /eventos.json
  
  def index
    @eventos = Evento.all
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
    @comentarios = ComentariosEvento.where("id_evento = ?",@evento.id)
    @imagenes = ImagenNombre.where("id_evento = ?",@evento.id)
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'El evento fue creado.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'El evento fue editado.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'El evento fue destruido.' }
      format.json { head :no_content }
    end
  end

  def crear_comentario
    if request.post?
      comentarios = (params[:comentarios])
      id = (params[:id])
      ComentariosEvento.create(:comentario=>comentarios,:id_evento=>id)
      redirect_to "/eventos/"+id
    end
  end
    
  def eliminar_comentario
    ComentariosEvento.find(params[:id]).destroy
    redirect_to "/eventos/"+(params[:evento_id])
    #redirect_to "/home/index"
  end

  def subir_imagen
    if request.post?
     archivo = params[:upload]
     id = (params[:id])
     if archivo != nil
      nombre_archivo = archivo['datafile'].original_filename  if  (archivo['datafile'] !='')
      tipo_archivo = nombre_archivo.split('.').last
      if ["png","jpg","jpeg"].include? tipo_archivo
        nombre_imagen = Time.now.to_i
        archivo = archivo['datafile'].read
        nombre_imagen_tipo = "#{nombre_imagen}." + tipo_archivo
        ImagenNombre.create(:nombre_imagen=>nombre_imagen_tipo, :id_evento => id)
        dir = (Rails.root.to_s)<<"/app/assets/images/eventos/"
        File.open(dir + nombre_imagen_tipo, "wb")  do |f|  
          f.write(archivo) 
        end
        redirect_to "/eventos/"+id
      else
        redirect_to "/eventos/"+id,notice: "el archivo no tiene el formato correcto"
      end
     else
      redirect_to "/eventos/"+id,notice: "el archivo no tiene el formato correcto"
     end
    else
      redirect_to "/eventos/"+id,notice: "el archivo no tiene el formato correcto"
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:nombre, :descripcion, :fecha)
    end
end

Club_De_Fans/app/helpers/eventos_helper.rb
module EventosHelper
end

Club_De_Fans/app/views/eventos/_form.html.erb
<%= form_for(@evento) do |f| %>
  <% if @evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evento.errors.count, "errores") %> Este evento no pudo ser guardado:</h2>

      <ul>
      <% @evento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label "Descripción del evento" %><br>
    <%= f.text_area :descripcion,cols: 60, rows: 10  %>
  </div>
  <div class="field">
    <%= f.label "Fecha del evento" %><br>
    <%= f.date_select :fecha,:order => [:day,:month,:year] %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Guardar" ,class: "btn btn-primary" %>
  </div>
<% end %>

Club_De_Fans/app/views/eventos/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Eventos</h1>

<ul class="list-group">
<% @eventos.each do |evento| %>
  <li class="list-group-item">
   <h2> Nombre: <%= evento.nombre %> </h2>
   <h3> Fecha: <%= evento.fecha %> </h3>
   <h3> <%= link_to 'Ver más', evento %> </h3>
    <%if iniciado? && es_admin? %>
        <%= link_to 'Editar evento', edit_evento_path(evento), class: "btn btn-sm btn-warning" %> 
        <%= link_to 'Eliminar el evento', evento, method: :delete, data: { confirm: '¿Seguro quieres borrar este evento y todos los comentarios y demás datos asociados a él?' }, class: "btn btn-sm btn-danger"%>
    <% end %>
  </li>
<% end %>
</ul>



<br>



Club_De_Fans/app/views/eventos/edit.html.erb
<h1>Editar Evento</h1>

<%= render 'form' %>

Club_De_Fans/app/views/eventos/index.html.erb
<%= render 'index' %>

Club_De_Fans/app/views/eventos/new.html.erb
<h1>Evento nuevo </h1>

<%= render 'form' %>

Club_De_Fans/app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>
<center>
	<h1>
		<%= @evento.nombre %>
	</h1>
</center>

<h3>
	<%= @evento.descripcion %>	
</h3>
<h3>
	<%= @evento.fecha %>	
</h3>  
  
<table>
	<% @imagenes.each do |im| %>
		<tr>
			<%=image_tag(((Rails.root.to_s)<<"/app/assets/images/eventos/")<<im.nombre_imagen,{:alt=>""})%>
		</tr>
	<% end %>
</table>


<h2>Comentarios:</h2>
<ul class="list-group">
	<% @comentarios.each do |c| %>
		<li class="list-group-item">
			<%=c.comentario %>
			<% if es_admin? %>
				<%= link_to "eliminar comentario", :controller=>"eventos", :action=>"eliminar_comentario", :id=> c.id, :evento_id=> @evento.id,class: "btn btn-primary"%>
			<% end %>
		</li>
			
		
	<% end %>
</ul>
<% if iniciado? %>
	<%= form_tag "crear_comentario", :method=>"post"  do %>
		<p>
		<%=label_tag "Escribe un comentario del evento" %> <br>
		<%= text_area_tag "comentarios", nil, cols: 60, rows: 2%> <br>
		<%= hidden_field_tag(:id, @evento.id) %>
		<%= submit_tag "Enviar comentarios", :confirm=>true, :value => "Enviar comentarios",class: "btn btn-primary" %>
		</p>
	<% end %>

	<%= form_tag "subir_imagen", :method=>"post", :multipart => true  do %>
		<p>
		<%= label_tag "Archivo a subir:" %> <br>
		<%= file_field 'upload', 'datafile' %></p>
		<%= hidden_field_tag(:id, @evento.id) %>
		<%= submit_tag "subir imagen", :confirm=>true, :value => "Subir imagen",class: "btn btn-primary" %>	
		</p>
	<% end %>
	<% if es_admin? %>
		<%= link_to 'Editar evento', edit_evento_path(@evento),class: "btn btn-warning" %>
	<% end %>
<% end %>