Club_De_Fans/config/routes.rb
Rails.application.routes.draw do
  
  
  get 'sessions/new'

  get 'home/index'

  get 'home/contacto'

  get 'home/quienes_somos'

  get 'home/lista_comentarios'

  get 'home/eliminar'

  post 'home/crear_contacto' 

  root 'home#index'

  get 'usuarios/signup', to: 'usuarios#new'
  resources :usuarios

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post '/eventos/crear_comentario'
  post '/eventos/subir_imagen'
  get '/eventos/eliminar_comentario'

  resources :eventos
end

Club_De_Fans/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClubDeFans</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="main-container" class="container-fluid">
      <div class="row">
        <div class="col-md-1">  
        </div>

        <div class="col-md-1">
          <%= link_to "Inicio", :controller=>"home", :action =>"index",class: 'btn btn-link' %>
        </div>
        <div class="col-md-1">
          <%= link_to "Contacto", :controller=>"home", :action =>"contacto" %>
        </div>
        <div class="col-md-1">
          <%= link_to "Quienes Somos", :controller=>"home", :action =>"quienes_somos" %>
        </div>
        <div class="col-md-1">
          <%= link_to "Registrarse", :controller=>"usuarios", :action =>"new" %>
        </div>
        <div class="col-md-1">
          <%= link_to "Iniciar sesión", :controller=>"sessions", :action =>"new" %>
        </div>
        <% if iniciado? %>
          <div class="col-md-1">
            <%= link_to "Perfil", usuario_actual %>  
          </div>
          <div class="col-md-1">
            <%= link_to "Cerrar sesión", logout_path, method: "delete" %>
          </div>
          <% if es_admin?%>
            <div class="col-md-1">
              <%= link_to "Mostrar usuarios",usuarios_path %>
            </div>
            <div class="col-md-1">
              <%= link_to "Mostrar comentarios", :controller=>"home", :action=>"lista_comentarios" %>
            </div>
            <div class="col-md-1"> 
              <%= link_to 'Añadir Evento', new_evento_path %>
            </div>
          <% end %>
        <% end %>
        <div class="col-md-1">  
        </div>
      </div>
      <div class="row">
        <div class="col-md-1">  
        </div>
        <div class="col-md-10">  
          <%= yield %>
        </div>
        <div class="col-md-1">  
        </div>
      </div>
    </div>
</div>
</body>
</html>