Club_De_Fans/config/routes.rb
Rails.application.routes.draw do
  
  
  get 'sessions/new'

  get 'home/index'

  get 'home/contacto'

  get 'home/quienes_somos'

  get 'home/lista_comentarios'

  get 'home/eliminar'

  post 'home/crear_contacto' 

  root 'home#index'

  get 'usuarios/signup', to: 'usuarios#new'
  resources :usuarios

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post '/eventos/crear_comentario'
  post '/eventos/subir_imagen'
  get '/eventos/eliminar_comentario'

  resources :eventos
end

Club_De_Fans/app/models/usuario.rb
class Usuario < ActiveRecord::Base
	before_save { self.email = email.downcase }

	validates :nombre, presence: true, length: {maximum: 50}
	validates :email, presence: true, length: {maximum: 100},
	format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i },
	uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, presence: true, length: {minimum: 4}

	def Usuario.digest(string)
    	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    	BCrypt::Password.create(string, cost: cost)
  	end
end

Club_De_Fans/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]
  before_action :usuario_iniciado, only: [:edit, :update,:show,:index]
  before_action :usuario_correcto, only: [:show,:edit,:update]
  before_action :usuario_admin, only: [:index, :destroy]
    # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'el usuario fue creado exitosamente.' }
        format.json { render :show, status: :created, location: @usuario }
        iniciar_sesion(@usuario)
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'El usuario se actualizó con éxito.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario se eliminó exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :email,:password, :password_confirmation)
    end

    
end

Club_De_Fans/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

Club_De_Fans/app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "errores") %> no se pudo registrar el  usuario:</h2>

      <ul>
        <li>El nombre no puede ser vacío.</li>
        <li>El email no puede ser vacío.</li>
        <li>El email debe tener un formato válido.</li>
        <li>La contraseña no puede ser vacía y debe tener al menos 4 caracteres.</li>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password%>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Vuelve a escribir el Password" %> <br>
    <%= f.password_field :password_confirmation %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Guardar", class: "btn btn-primary"%>
  </div>
<% end %>

Club_De_Fans/app/views/usuarios/edit.html.erb
<h1>Editar Usuario</h1>

<%= render 'form' %>

Club_De_Fans/app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Usuarios.</h1>

<ul class="list-group">
  <% @usuarios.each do |u| %>
    <li class="list-group-item">
      <h4>Nombre: </h4> <%=u.nombre %> <br>
      <h4>Email: </h4> <%=u.email %> <br>
      <%if !u.tipo  %>
        <%= link_to 'Eliminar usuario', u, method: :delete, data: { confirm: '¿Estás seguro?' },class: "btn btn-danger" %>
      <% end %>
    </li>
  <% end %>
</ul>

Club_De_Fans/app/views/usuarios/new.html.erb
<h1>Usuario Nuevo</h1>

<%= render 'form' %>

Club_De_Fans/app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<%= link_to 'Editar', edit_usuario_path(@usuario) %> 